services:
  ebill-backend:
    image: tushar26g/ebill-backend
    container_name: ebill-backend
    ports:
      - "5000:5000"
    #    networks:
    #      fintrack:
    #        ipv4_address: 172.28.1.7
    environment:
      - MYSQL_HOST=172.16.139.213
      - MYSQL_PORT=3308
    depends_on:
        mydb:
          condition: service_healthy

  mydb:
    image: mysql:latest
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD","ls"]
    container_name: database-container
    #    networks:
    #      fintrack:
    #        ipv4_address: 172.28.1.8
    environment:
      - MYSQL_ROOT_PASSWORD=password
    #      - MYSQL_DATABASE=EBillDataCenter
    volumes:
      - /home/tuhar/mysql_volume:/var/lib/mysql

  ebill-frontend:
    image: tushar26g/ebill-frontend
    container_name: ebill-frontend
    # Keep stdin_open because we don't want this container to exit immediately which it
    # otherwise would have because there's no foreground processes
    stdin_open: true
    ports:
      - "3000:3000"
#    networks:
#      fintrack:
#        ipv4_address: 172.28.1.6
    depends_on:
      - ebill-backend


    # Using Docker volume for persisting logs
    # ./backend/logs refers to the path /home/backend/logs on the host machine
    # and we're linking it to logs folder on the container machine where Morgan logger logs its output



#networks:
#  fintrack:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.28.1.0/24

#version: '3.5'
#services:
#  app:
#    build:
#      context: .
#    volumes:
#      - /Users/boppanavenkatesh/Desktop/mysql_volume:/var/lib/mysql
#
#  frontend:
#    image: venkateshkvrs/ebill-frontend
#    ports:
#      - "3000:3000"
#    container_name: frontend-container
#    command: npm start
#
#  backend:
#    image: venkateshkvrs/ebill-backend
#    ports:
#      - "5000:5000"
#    container_name: backend-container
#    environment:
#      - MYSQL_HOST=mydb
#      - MYSQL_PORT=3307
#    depends_on:
#      - mydb
#
#  mydb:
#    image: mysql:latest
#    ports:
#      - "3307:3306"
#    container_name: database-container
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=EBillDataCenter
#version: '3'
#
#services:
#  mysqldb:
#    container_name: mysqldb
#    image: mysql
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_DATABASE: EBillDataCenter
#      MYSQL_ROOT_PASSWORD: password
#  backend:
#    image: backend
#    build:
#      context: .
#      dockerfile: backend/Dockerfile
#    ports:
#      - 5000:5000
#    environment:
#      MYSQL_HOST: mysqldb
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password
#      MYSQL_PORT: 3306
#    depends_on:
#      - mysqldb
#  frontend:
#    image: frontend
#    build:
#      context: .
#      dockerfile: frontend/Dockerfile
#    ports:
#      - 3000:3000