version: '3.9'
networks:
  ebill-network:
volumes:
  database-volume:
services:
  mydb:
    image: mysql:latest
    #    ports:
    #      - "3308:3306"
    healthcheck:
      test: [ "CMD","ls" ]
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: EBillDataCenter
    volumes:
      - ebill-volume:/var/lib/mysql
    networks:
      - ebill-network
  ebill-backend:
    image: tushar26g/ebill-backend
    container_name: ebill-backend
    ports:
      - "5000:5000"
    environment:
      MYSQL_URL: jdbc:mysql://mydb:3306/EBillDataCenter?createDatabaseIfNotExist=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
    networks:
      - ebill-network
    depends_on:
      mydb:
        condition: service_healthy
  ebill-frontend:
    image: tushar26g/ebill-frontend
    container_name: ebill-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - ebill-network
    depends_on:
      - ebill-backend